/* This file is a part of lynx-compat-data
 * See LICENSE file for more information. */

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source schema files in
 * schemas/*, and run "npm run gentypes" to regenerate this file.
 */

/**
 * The names of the known platforms.
 */
export type PlatformName =
  | 'android'
  | 'clay_android'
  | 'clay_macos'
  | 'clay_windows'
  | 'ios'
  | 'web_lynx';

export type VersionValue = string | boolean | null;

/**
 * This interface was referenced by `PlatformDataFile`'s JSON-Schema
 * via the `definition` "platforms".
 */
export type Platforms = Record<PlatformName, PlatformStatement>;
/**
 * This interface was referenced by `PlatformDataFile`'s JSON-Schema
 * via the `definition` "platform_type".
 */
export type PlatformType = 'native' | 'web' | 'clay';
/**
 * This interface was referenced by `PlatformDataFile`'s JSON-Schema
 * via the `definition` "platform_status".
 */
export type PlatformStatus = 'retired' | 'current' | 'beta' | 'planned';

/**
 * This interface was referenced by `PlatformDataFile`'s JSON-Schema
 * via the `definition` "platform_statement".
 */
export interface PlatformStatement {
  /**
   * The platform brand name (e.g. iOS, Android, Web, etc.).
   */
  name: string;
  /**
   * The type of the platform (e.g. native, web, or clay).
   */
  type: PlatformType;
  /**
   * The known versions of this platform.
   */
  releases: { [version: string]: ReleaseStatement };
}
/**
 * This interface was referenced by `PlatformDataFile`'s JSON-Schema
 * via the `definition` "release_statement".
 */
export interface ReleaseStatement {
  /**
   * The date on which this version was released, formatted as `YYYY-MM-DD`.
   */
  release_date?: string;
  /**
   * A link to the release notes or changelog for a given release.
   */
  release_notes?: string;
  /**
   * A property indicating where in the lifetime cycle this release is in (e.g. current, retired, beta, nightly).
   */
  status: PlatformStatus;
}

/**
 * This interface was referenced by `CompatDataFile`'s JSON-Schema definition
 * via the `patternProperty` "^(?!__compat)(?!lynx_extensions)[a-zA-Z_0-9-$@]*$".
 *
 * This interface was referenced by `CompatDataFile`'s JSON-Schema
 * via the `definition` "identifier".
 */
export type Identifier = { [key: string]: Identifier } & {
  __compat?: CompatStatement;
};
/**
 * This interface was referenced by `CompatDataFile`'s JSON-Schema definition
 * via the `patternProperty` "^lynx_extensions*$".
 */
export type LynxExtensionsIdentifier = Identifier;
/**
 * The data for the support of each platform, containing a `support_statement` object for each platform identifier with information about versions, prefixes, or alternate names, as well as notes.
 */
export type SupportBlock = Partial<Record<PlatformName, SupportStatement>>;
/**
 * This interface was referenced by `CompatDataFile`'s JSON-Schema
 * via the `definition` "support_statement".
 */
export type SupportStatement =
  | SimpleSupportStatement
  | SimpleSupportStatement[];
/**
 * This interface was referenced by `CompatDataFile`'s JSON-Schema
 * via the `definition` "lynx_extensions_identifier".
 */
export type LynxExtensionsIdentifier1 = { [key: string]: Identifier } & {
  __compat?: CompatStatement;
};

/**
 * This interface was referenced by `CompatDataFile`'s JSON-Schema definition
 * via the `patternProperty` "^__compat$".
 *
 * This interface was referenced by `CompatDataFile`'s JSON-Schema
 * via the `definition` "compat_statement".
 */
export interface CompatStatement {
  /**
   * A string containing a human-readable description of the feature.
   */
  description?: string;
  /**
   * An optional URL to the MDN documentation for the feature, used to link from the Lynx doc website.
   */
  mdn_url?: string;
  /**
   * A URI that points to the lynx docs page documenting the feature. This URI is left in relative form to allow for converting into both internal and external URIs in the future.
   */
  lynx_path?: string;
  /**
   * An optional URL or array of URLs, each of which is for a specific part of a specification in which this feature is defined. Each URL must contain a fragment identifier.
   */
  spec_url?: string | string[];
  /**
   * An optional array of strings allowing to assign tags to the feature.
   *
   * @minItems 1
   */
  tags?: string[];
  /**
   * The path to the file that defines this feature in lynx-compat-data, relative to the repository root. Useful for guiding potential contributors towards the correct file to edit. This is automatically generated at build time and should never manually be specified.
   */
  source_file?: string;
  support: SupportBlock;
  status?: StatusBlock;
}
/**
 * An object containing information about the stability of the feature.
 */
export interface StatusBlock {
  /**
   * A boolean value that indicates the general stability of this feature. This value will be true if the feature was implemented in Lynx recently. This value will be false if the feature had been implemented over two years ago in Lynx.
   */
  experimental: boolean;
  /**
   * A boolean value that indicates whether the feature is no longer recommended. It might be removed in the future or might only be kept for compatibility purposes. Avoid using this functionality.
   */
  deprecated: boolean;
}
/**
 * This interface was referenced by `CompatDataFile`'s JSON-Schema
 * via the `definition` "simple_support_statement".
 */
export interface SimpleSupportStatement {
  /**
   * A string (indicating which Lynx version added this feature), the value true (indicating support added in an unknown version), the value false (indicating the feature is not supported), or the value null (indicating support is unknown).
   */
  version_added: VersionValue;
  /**
   * A string, indicating which Lynx version removed this feature, or the value true, indicating that the feature was removed in an unknown version.
   */
  version_removed?: VersionValue;
  /**
   * A string, indicating the last Lynx version that supported this feature, or the value true, indicating that the feature was removed in an unknown version. This is automatically generated.
   */
  version_last?: VersionValue;
  /**
   * A prefix to add to the sub-feature name (defaults to empty string). If applicable, leading and trailing '-' must be included.
   */
  prefix?: string;
  /**
   * An alternative name for the feature, for cases where a feature is implemented under an entirely different name and not just prefixed.
   */
  alternative_name?: string;
  /**
   * An optional array of objects describing flags that must be configured for Lynx to support this feature.
   *
   * @minItems 1
   */
  flags?: FlagStatement[];
  /**
   * An optional changeset/commit URL for the revision which implemented the feature in the Lynx source code, or the URL to the bug tracking the implementation.
   */
  impl_url?: string | string[];
  /**
   * A boolean value indicating whether or not the implementation of the sub-feature deviates from the Lynx specification in a way that may cause compatibility problems. It defaults to false (no interoperability problems expected). If set to true, it is recommended that you add a note explaining how it diverges from the standard (such as that it implements an old version of the standard, for example).
   */
  partial_implementation?: true;
  /**
   * A string or array of strings containing additional information.
   */
  notes?: string | string[];
}
/**
 * This interface was referenced by `CompatDataFile`'s JSON-Schema
 * via the `definition` "flag_statement".
 */
export interface FlagStatement {
  /**
   * An enum that indicates the flag type.
   */
  type: 'preference' | 'runtime_flag';
  /**
   * A string giving the name of the flag or preference that must be configured.
   */
  name: string;
  /**
   * A string giving the value which the specified flag must be set to for this feature to work.
   */
  value_to_set?: string;
}
